### PR TITLE
Namespace translation

### PR DESCRIPTION
**Pull request by grechaw**
Hi @bsrikan This is yet another PR, which incidentally contains all the commits from #354 , but also that fixes issue #352, getting namespace support into version translator. 

Since technically this is finishing up feature-complete, I made a separate one for it rather than augmenting 'blacklist'.

I can merge all at once if you're going to be ready for it, or take care of them separately.

### CODE REVIEW

**Comment by bsrikan** [comment]
Looking into it now.

**Comment by bsrikan** [comment]
@grechaw Should the convert-instance-X() that is commented out include this change
```
before:
json:object()
=>map:with("$type", "Customer" )

now:
es:init-instance($source, "Customer")
```

**Comment by grechaw** [comment]
yes, ill add it, good catch

**Comment by grechaw** [comment]
Oh, yes, that change was intended.  I thought you were finding a place I'd meant to make that change. 
You'll find that that change is consistent with how i refactored the instance converter module last minor release.

**Comment by grechaw** [comment]
OK This PR has been updated to reflect comments and fixes and new tests.
It looks ready to merge.

**Pull request merged**
