### PR TITLE
Es extract array

### LINKED ISSUE #149: extract-array does not extract a sequence below a property
Use Northwind-0.0.1.xqy.

extract-instance-Order shoudl work out of the box for northwind data.  Example, 

/MarkLogic/git/entity-services/entity-services-e2e/data/northwind/orders/10249.xml

It looks as though extract-array needs a /\* on the end of its last line, but we need to verify and test this hypothesis

### PR DESCRIPTION
**Pull request by grechaw**
Hi Srikanth, here is a PR that will cause some impact.

1. es:extract-array is a new function.  Like es:optional, I pulled it out from generated code into the main entity services module.
2. fixes  #149 
3. editorconfig is a plugin that enforces things like tabs and spaces for ones proejct.
4. updates ml-gradle.
5. took out DMSSK dependency in examples and added java client api, which now includes DMSDK.

e2e will have to mirror #5.  there are some key updates.

### CODE REVIEW

**Comment by grechaw** [comment]
Oh, I also included the commits from your PR #164, ready to merge with this one.

**Comment by bsrikan** [comment]
Looks like a great PR. Will .editorconfig override the tab/spacing set in my eclipse?

**Comment by jmakeig** [comment]
I think you need a plugin in Eclipse to use editorconfig.

**Comment by bsrikan** [comment]
Got it. Thanks @jmakeig 

Please go ahead and merge @grechaw . Once merged I will absorb changes and create a PR with my tests for #149 .

**Pull request merged**
