### PR TITLE
Major e2e updates

### PR DESCRIPTION
**Pull request by bsrikan**
@grechaw @rashiatmarklogic 
Please merge this PR that includes major updates to e2e.

### CODE REVIEW

**Comment by grechaw** [comment]
This is a rather large PR -- I'll download it today and give it a whirl before merging.  @rashiatmarklogic I'll also keep an eye out for whatever you happen across.

**Comment by grechaw** [comment]
There are two qc workspaces in the e2e-nwind directory, maybe you wanted to remove one of them, as it has a lot of code from the examples dir.

**Comment by rashiatmarklogic** [comment]
@grechaw From my perspective, I would like this PR merged to develop as soon as possible since then I can grab the changes and try to play around with e2e. 

From my side its a go!

**Comment by grechaw** [comment]
OK, I'll go ahead and merge now.  Srikanth and I had some time to go over questions and it seems to be in good shape for wider review.

**Comment by rashiatmarklogic** [comment]
Great !

**Pull request merged**
