### PR TITLE
Adding Test files for Required testing and SearchOptions. Will obviously

### PR DESCRIPTION
**Pull request by rashiatmarklogic**
modify these files and build more test cases upon them.

This PR only has the unit test for Required and searchoptions features. But, this is added to functionaltests as sanity and QA will modify these files to build upon functional testcases.

### CODE REVIEW

**Comment by rashiatmarklogic** [comment]
Please merge to develop - there is nothing to verify in this commit, only small changes to SearchOptionsGenerate key since my ET doc for that test differed.

**Comment by grechaw** [comment]
OK will do

**Comment by rashiatmarklogic** [comment]
@bsrikan : including you as well for a heads up.

**Comment by bsrikan** [comment]
Here is my change for bug 40403. 
https://github.com/marklogic/entity-services/commit/3ea053bee9b382f534db85952b319d120acab2a7

**Pull request merged**
