### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by grechaw**
Two validation bugfixes.

The one for Issue #77 may have rippling effects through keys.  It is now considered invalid to use a property name that matches a type name.
For these (and really, for all property names) I suggest using lowercase names to avoid this validation issue.

### CODE REVIEW

**Comment by grechaw** [comment]
Take a look to see when you want to absorb.  Probably a few key updates will be required.

**Comment by bsrikan** [comment]
I will take a look

**Comment by bsrikan** [comment]
Go ahead and merge Charles. I understand the changes and will create separate model documents(invalid ones) to validate the error messages added.

**Comment by grechaw** [comment]
This was merged.

**Pull request closed without merging**
