### PR TITLE
Improved testing performance and stylistic updates

### PR DESCRIPTION
**Pull request by grechaw**
This PR has no functional changes, but it avoids loading unused data for each test, and so speeds things up considerably.

### CODE REVIEW

**Comment by bsrikan** [comment]
This is good. @grechaw I have had this suggestion in my mind for some time now and since this PR is about improving test performance, I thought I will give it a go.
Do we also have to load the test data via setupClients() call, which loads the same entityTypes and source files, before every test. Instead, can we not have an annotation @BeforeClass in EntityServicesTestBase.class file before setupClients() method and load the ET and source files just once to be used across all the tests.

**Comment by grechaw** [comment]
On further consideration, there's one test in here that will not work on Rashi's setup, where the tests and server are on different machines.  I think I should rethink that one (invalid-entity-types).

In the new scenario, each test takes care of its own loading; setupClients only gets the database connections ready.

**Comment by bsrikan** [comment]
Ok I see. I was looking at TestSetup.java file in functionaltests only and didnt look at the other one. TestSetup.java file for UnitTest has the instance.loadXX commented but they arent for functionaltests.

We have a separate instance.loadInvalidEntityTypes() call that takes care of the problem you mention. Maybe if you add that in unit test then it might work with Rashi's setup.

**Comment by grechaw** [comment]
I've updated the PR to not have the issue from before.  I gave back a little speed, but the improvement is still good.  I'll clean up the commit a little more, then update this PR again and push

**Comment by rashiatmarklogic** [comment]
Sounds good Charles, maybe you can push the changes for Unit test and then we can discuss these in next meeting and see if we can improve the test cases in Functional area as well.

**Pull request merged**
