### PR TITLE
PR with functionaltests for bugfixes pr and e2e updates

### PR DESCRIPTION
**Pull request by bsrikan**
This PR now includes updates to functional tests as a result of bugfixes PR from @grechaw.
FYI @rashiatmarklogic

### CODE REVIEW

**Comment by bsrikan** [comment]
I will add more commits with e2e updates to this PR in a while.

**Comment by bsrikan** [comment]
@grechaw I am now thinking I should probably create a separate PR for e2e stuff as I have few things to discuss with you on e2e. 
It will be great if we can get this PR merged to develop so functional tests will run OK in regression.

**Comment by grechaw** [comment]
OK, so all ready now from your perspective?

**Comment by bsrikan** [comment]
Yes @grechaw all set.

**Pull request merged**
