### PR TITLE
Issue #235 bring examples up to date for EA 4 code.

### PR DESCRIPTION
**Pull request by grechaw**
This PR improves example code for EA-4.

I reacted wrongly to some late Java Client changes, and this PR fixes those.

It also introduces a couple more QConsole workspaces to help with suppliers and person, which had been lacking.  They are simple but ready for review.

### CODE REVIEW

**Comment by bsrikan** [comment]
Working on it. Will have an update before WG meeting

**Comment by bsrikan** [comment]
1. Count issue for non raw docs (since there are 2 versions of race envelopes)
Non raw is 1314, including 4 from race-0.0.2-envelopes collection

2. Is it understood that folks have to change $path to where entity-services is checked out for QC tabs 2,3,11?

Otherwise looks OK.

**Comment by grechaw** [comment]
Thanks for those catches.  I'll make it more obvious about path, and will change count too.

**Comment by jmakeig** [comment]
I’m about to dig in on this to update the EA sitelet.

**Comment by bsrikan** [comment]
Javascript optic queries for Person and Suppliers are having issues.

Suppliers: `OPTIC-INVALARGS: fn.error(null, 'OPTIC-INVALARGS', 'cannot '+joinName+'() without right plan'); -- Invalid arguments: cannot joinInner() without right plan`

Person: `OPTIC-INVALARGS: fn.error(null, 'OPTIC-INVALARGS', errMsg+arg); -- Invalid arguments: cannot call pattern() with invalid predicates : sem.iri("http://www.w3.org/1999/02/22-rdf-syntax-ns#type")`

Informed Charles and he feels there might be an optic js bug.

**Comment by jmakeig** [comment]
Initial set-up looks good to me on a virgin install of MarkLogic 9.0-20161216 and entity-services feab903fdbd213fc98bd74b84667686edd2ebef9. 

```
Raw docs (1354 expected): 
1354
Non raw (1314 expected): 
1314
Race envelopes (4 expected): 
4
Run envelopes (1300 expected): 
1300
Collection names
angel-island
csv
http://marklogic.com/entity-services/models
race-0.0.2-envelopes
race-envelopes
raw
reference
run-envelopes
```

**Pull request merged**
