### PR TITLE
Update to marklogic-client-api issue #224

### PR DESCRIPTION
**Pull request by grechaw**
Hi @rashiatmarklogic  this change updates the gradle deps to the new name for java-client-api.

I updated e2e and examples directory.  If you think this works, ill write mr triage.

### CODE REVIEW

**Comment by rashiatmarklogic** [comment]
I will update my repo and try this out. Shall update you by eod.

**Comment by rashiatmarklogic** [comment]
Do not think ist working still.

**Comment by grechaw** [comment]
OK I did some more updates, this time in e2e code.

**Comment by grechaw** [comment]
We OK with this one now?  I'll assign @bsrikan too.

**Comment by bsrikan** [comment]
@grechaw testVersionComparison() is failing in regression today. Can you please check that it is running OK with your changes

**Comment by grechaw** [comment]
Commit added to update key.  Key changed as a result of difference for handling local and absolute refs.

**Comment by grechaw** [comment]
merged alonside other PR, closing

**Pull request closed without merging**
