### PR TITLE
remove log, extra function

### PR DESCRIPTION
**Pull request by grechaw**
Left a log statement in the code, and also left in the function that turned out to be rather unnecessary.

### CODE REVIEW

**Comment by paxtonhare** [comment]
@grechaw Here's a suggestion for some further cleanup. 

Instead of this:
```xquery
    let $instance := json:object()
        =>map:with('$attachments', $source)
(: The previous line adds the original source document as an attachment.            :)
(: If the source document is JSON, remove the previous line and replace it with     :)
(: =>map:with('$attachments', xdmp:quote($source))                                  :)
```

how about give them a function to automagically do it:

```xquery
    let $instance := json:object()
        (: Add the original source document as an attachment.            :)
        => map:with('$attachments',
            if (prefix:is-json($source)) then
                xdmp:quote($source)
            else
                $source
        )
```

Here's the is-json function:
```xquery
declare function prefix:is-json($input)
{
  let $o :=
    if ($input instance of document-node()) then
      $input/node()
    else
      $input
  return
    typeswitch($o)
      case object-node() |
        array-node() |
        number-node() |
        boolean-node() |
        null-node() return fn:true()
      default return fn:false()
};
```

You could even put is-json into es: if you were feeling crazy.

**Comment by grechaw** [comment]
i guess it's not really a decision, just something you gotta do for JSON.
Seems like automagical is OK in this case.

**Comment by bsrikan** [comment]
Please go ahead Charles.

**Comment by grechaw** [comment]
Maybe just inline.... won't ever be a number, boolean or null node so it's pretty compact.

```
  (: Add the original source document as an attachment.            :)
        =>map:with('$attachments'
            typeswitch($source-node)
            case object-node() then xdmp:quote($source)
            case array-node() then xdmp:quote($source)
            else $source)
```

**Comment by grechaw** [comment]
Thanks @bsrikan

**Comment by grechaw** [comment]
I think I finally got this right... will merge after tests confirm.

**Comment by grechaw** [comment]
This PR was merged on the command line, closing manually

**Pull request closed without merging**
