### PR TITLE
Json arrays

### PR DESCRIPTION
**Pull request by grechaw**
This PR delivers a method for ensuring json array serialization for instance data, and adjusts the schema generation for models accordingly.

### CODE REVIEW

**Comment by grechaw** [comment]
I'm verifying my tests now, but I think this is all set to go @bsrikan  It requires quite a few key updates, for test instance creation and schemas.

**Comment by bsrikan** [comment]
Looks good to me Charles. I am absorbing your changes now and will work on updating tests/keys.
Lets merge this PR tomorrow.

**Comment by bsrikan** [comment]
You can merge this PR now @grechaw

**Comment by bsrikan** [comment]
Merged this code to develop.

**Pull request merged**
