### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by grechaw**
Hi @bsrikan @rashiatmarklogic , I've made this one last push to EA-3 niceness.

This PR delivers comments and cleanup, and provides one remaining fix for 40486.

Since comments have changed, this will trash all the keys for conversion module text, but for me it's a big improvement in readability.  If you get word to me this weekend or Monday, I'll merge this bug and move most of my remaining bugs to test or push them to ea-4.

### CODE REVIEW

**Comment by grechaw** [comment]
So I'm heading out of town until Thursday.  I would love to push this PR to develop on friday so as to give time to adjust keys.  So just let me know when you're ready for it.

**Comment by rashiatmarklogic** [comment]
Sure, go ahead will try to absorb. Mainly conversion module keys will be changed. Ok noted. You can merge.

**Comment by grechaw** [comment]
Thanks @rashiatmarklogic .  will make a new build today and run all test than merge (just cause I miss yalls so much)

**Comment by grechaw** [comment]
Merged this.  Thanks folks!

**Pull request closed without merging**
