### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by grechaw**
Hi folks, take a look at this examples PR.  It should solve the deployment issues, by figuring out the project dir from the system.

@jmakeig @sammefford @bsrikan this change should streamline examples deployment a bit.

Also in this PR I broke up the example code into smaller classes.

### CODE REVIEW

**Comment by bsrikan** [comment]
Looks ok to me.

**Comment by jmakeig** [comment]
I’m getting an `NPE` with `gradle run`. It looks logback-related:

```
Connected to daemon DaemonInfo{pid=28053, address=[405be4b4-aa02-4126-8a01-85d7731588c8 port:63124, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=ac02f93c-3c5c-4544-b406-c73bb7bcad1a,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home,daemonRegistryDir=/Users/jmakeig/.gradle/daemon,pid=28053,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=3972edc1-4402-401e-9701-c90ef1ac79f5.1, currentDir=/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services-examples}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@6f10d5b6 from daemon DaemonInfo{pid=28053, address=[405be4b4-aa02-4126-8a01-85d7731588c8 port:63124, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=ac02f93c-3c5c-4544-b406-c73bb7bcad1a,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home,daemonRegistryDir=/Users/jmakeig/.gradle/daemon,pid=28053,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 28053). The daemon log file: /Users/jmakeig/.gradle/daemon/2.10/daemon-28053.out.log
Starting 5th build in daemon [uptime: 11 mins 39.133 secs, performance: 98%, memory: 47% of 954.7 MB]
Executing build with daemon context: DefaultDaemonContext[uid=ac02f93c-3c5c-4544-b406-c73bb7bcad1a,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home,daemonRegistryDir=/Users/jmakeig/.gradle/daemon,pid=28053,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Starting Build
Settings evaluated using settings file '/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/settings.gradle'.
Projects loaded. Root project using build file '/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/build.gradle'.
Included projects: [root project 'entity-services-parent', project ':entity-services', project ':entity-services-e2e', project ':entity-services-examples', project ':entity-services-functionaltests']
Evaluating root project 'entity-services-parent' using build file '/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/build.gradle'.

Initializing ml-gradle
Admin host: localhost
Admin username: admin
App name: entity-services-test
Schemas path: src/main/ml-schemas
App host: localhost
App REST port: 8201
REST admin username: admin
Manage host: localhost
Manage username: admin
Manage admin username: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, admin username: admin]
Initialized ManageClient with base URL of: http://localhost:8002
Initializing instance of DefaultModulesLoader
Finished initializing ml-gradle

Evaluating project ':entity-services' using build file '/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services/build.gradle'.

Initializing ml-gradle
Admin host: localhost
Admin username: admin
App name: entity-services-test
Schemas path: src/main/ml-schemas
App host: localhost
App REST port: 8201
REST admin username: admin
Manage host: localhost
Manage username: admin
Manage admin username: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, admin username: admin]
Initialized ManageClient with base URL of: http://localhost:8002
Initializing instance of DefaultModulesLoader
Finished initializing ml-gradle

Evaluating project ':entity-services-e2e' using build file '/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services-e2e/build.gradle'.

Initializing ml-gradle
Admin host: localhost
Admin username: admin
App name: entity-services-e2e
Schemas path: src/main/ml-schemas
App host: localhost
App REST port: 8202
REST admin username: admin
Manage host: localhost
Manage username: admin
Manage admin username: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, admin username: admin]
Initialized ManageClient with base URL of: http://localhost:8002
Initializing instance of DefaultModulesLoader
Finished initializing ml-gradle

Evaluating project ':entity-services-examples' using build file '/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services-examples/build.gradle'.

Initializing ml-gradle
Admin host: localhost
Admin username: admin
App name: entity-services-examples
Schemas path: src/main/ml-schemas
App host: localhost
App REST port: 8203
REST admin username: adam
Module permissions: rest-admin,read,rest-admin,update,rest-extension-user,execute,rest-reader,read,race-reader,execute
Manage host: localhost
Manage username: adam
Manage admin username: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: adam, admin username: admin]
Initializing ManageClient with admin config, admin user: admin
Initialized ManageClient with base URL of: http://localhost:8002
Initializing instance of DefaultModulesLoader
Finished initializing ml-gradle

Evaluating project ':entity-services-functionaltests' using build file '/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services-functionaltests/build.gradle'.

Initializing ml-gradle
Admin host: localhost
Admin username: admin
App name: entity-services-test
Schemas path: src/main/ml-schemas
App host: localhost
App REST port: 8201
REST admin username: admin
Manage host: localhost
Manage username: admin
Manage admin username: admin
Initializing ManageClient with manage config of: [ManageConfig host: localhost, port: 8002, username: admin, admin username: admin]
Initialized ManageClient with base URL of: http://localhost:8002
Initializing instance of DefaultModulesLoader
Finished initializing ml-gradle

All projects evaluated.
Selected primary task 'run' from project :entity-services-examples
Tasks to be executed: [task ':entity-services-examples:compileJava', task ':entity-services-examples:processResources', task ':entity-services-examples:classes', task ':entity-services-examples:run']
In-memory cache of /Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/.gradle/2.10/taskArtifacts/fileHashes.bin: Size{319}, CacheStats{hitCount=293, missCount=319, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/.gradle/2.10/taskArtifacts/outputFileStates.bin: Size{17}, CacheStats{hitCount=17, missCount=3, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/.gradle/2.10/taskArtifacts/fileSnapshots.bin: Size{48}, CacheStats{hitCount=0, missCount=3, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/.gradle/2.10/taskArtifacts/taskArtifacts.bin: Size{13}, CacheStats{hitCount=2, missCount=13, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
:entity-services-examples:compileJava (Thread[Daemon worker Thread 2,5,main]) started.
:entity-services-examples:compileJava
Skipping task ':entity-services-examples:compileJava' as it is up-to-date (took 0.028 secs).
:entity-services-examples:compileJava UP-TO-DATE
:entity-services-examples:compileJava (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.03 secs.
:entity-services-examples:processResources (Thread[Daemon worker Thread 2,5,main]) started.
:entity-services-examples:processResources
Skipping task ':entity-services-examples:processResources' as it is up-to-date (took 0.001 secs).
:entity-services-examples:processResources UP-TO-DATE
:entity-services-examples:processResources (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.006 secs.
:entity-services-examples:classes (Thread[Daemon worker Thread 2,5,main]) started.
:entity-services-examples:classes
Skipping task ':entity-services-examples:classes' as it has no actions.
:entity-services-examples:classes UP-TO-DATE
:entity-services-examples:classes (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.001 secs.
:entity-services-examples:run (Thread[Daemon worker Thread 2,5,main]) started.
:entity-services-examples:run
Executing task ':entity-services-examples:run' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java''. Working directory: /Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services-examples Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services-examples/build/classes/main:/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data integration/entity-services/examples/entity-services/entity-services-examples/build/resources/main:/Users/jmakeig/.m2/repository/com/marklogic/data-movement/1.0-SNAPSHOT/data-movement-1.0-SNAPSHOT.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.7/9865cf6994f9ff13fce0bf93f2054ef6c65bb462/logback-classic-1.1.7.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-csv/2.7.0/28adc7ccaececbbff99d2997fe8ba9061cc77037/jackson-dataformat-csv-2.7.0.jar:/Users/jmakeig/.m2/repository/com/marklogic/java-client-api/4.0-SNAPSHOT/java-client-api-4.0-SNAPSHOT.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.sun.jersey/jersey-core/1.17/ea723f958123e794f5c08fc0baa92578c72eef96/jersey-core-1.17.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.1.7/7873092d39ef741575ca91378a6a21c388363ac8/logback-core-1.1.7.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.20/867d63093eff0a0cb527bf13d397d850af3dcae3/slf4j-api-1.7.20.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.7.0/7d3430de9f2b600b074ba3bc007edcfbc4bbf4fb/jackson-databind-2.7.0.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.sun.jersey/jersey-client/1.17/2496bd961e09b4863d93588840c63f4d7b18a022/jersey-client-1.17.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.sun.jersey.contribs/jersey-apache-client4/1.17/36626bd5d05d45e8968d72cbe981dc757659987/jersey-apache-client4-1.17.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.sun.jersey.contribs/jersey-multipart/1.17/ddc8564845fd1096dea66c82ff4154017fb9af8c/jersey-multipart-1.17.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/org.jvnet.mimepull/mimepull/1.9.4/6ffca64fe0209a94c5a973a32e93b5eae0ac384e/mimepull-1.9.4.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.1.1/3d1d918f32709e33ba7ddb2c4e8d1c543ebe713e/httpclient-4.1.1.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/org.jvnet/mimepull/1.6/9a108888661e4c47edec899b796c91557ebf3a35/mimepull-1.6.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.1/33fc26c02f8043ab0ede19eadc8c9885386b255c/httpcore-4.1.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.1.1/5043bfebc3db072ed80fbd362e7caf00e885d8ae/commons-logging-1.1.1.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.4/4216af16d38465bbab0f3dff8efa14204f7a399a/commons-codec-1.4.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.7.0/5f2bfd0866bcacbcc7c25ce25f80b5aeed0f72f/jackson-core-2.7.0.jar:/Users/jmakeig/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.7.0/19f42c154ffc689f40a77613bc32caeb17d744e3/jackson-annotations-2.7.0.jar com.marklogic.entityservices.examples.ExamplesLoader
Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java''
15:41:38,863 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:41:38,863 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:41:38,863 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/jmakeig/Workspaces/marklogic-9-ea-sitelet/data%20integration/entity-services/examples/entity-services/entity-services-examples/build/resources/main/logback.xml]
15:41:38,937 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:41:38,939 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:41:38,944 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:41:38,965 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.marklogic.client] to INFO
15:41:38,965 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.marklogic.client] to false
15:41:38,965 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.marklogic.client]
15:41:38,965 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.marklogic.semantics] to DEBUG
15:41:38,965 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.marklogic.semantics] to false
15:41:38,965 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.marklogic.semantics]
15:41:38,965 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http] to INFO
15:41:38,965 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.apache.http] to false
15:41:38,965 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.apache.http]
15:41:38,966 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.marklogic.entityservices] to INFO
15:41:38,966 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.marklogic.entityservices] to false
15:41:38,966 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[com.marklogic.entityservices]
15:41:38,966 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
15:41:38,966 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:41:38,967 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:41:38,974 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4ca8195f - Registering current configuration as safe fallback point
Exception in thread "main" java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.marklogic.entityservices.examples.ExamplesBase.<init>(ExamplesBase.java:60)
	at com.marklogic.entityservices.examples.AsIsLoader.<init>(AsIsLoader.java:27)
	at com.marklogic.entityservices.examples.ExamplesLoader.main(ExamplesLoader.java:35)
:entity-services-examples:run FAILED
:entity-services-examples:run (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.264 secs.

FAILURE: Build failed with an exception.
```

**Comment by jmakeig** [comment]
My previous comment referenced 239002dd19d050b41519e0c32979c99e3284a875.

**Comment by jmakeig** [comment]
Actually, `ExamplesBase` is not finding my `application.properties`: 

```
Exception in thread "main" java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at com.marklogic.entityservices.examples.ExamplesBase.<init>(ExamplesBase.java:60)
	at com.marklogic.entityservices.examples.AsIsLoader.<init>(AsIsLoader.java:27)
	at com.marklogic.entityservices.examples.ExamplesLoader.main(ExamplesLoader.java:33)
```

**Comment by jmakeig** [comment]
`entity-services/entity-services-examples/src/main/resources/.gitignore` still includes `application.properties`. Should it not be there and be checked in?

**Comment by bsrikan** [comment]
I didnt face any issue post "../gradlew run" from examples dir.
Charles is creating application.properties runtime and projectDir points to examples folder. gitignore should have application.properties.

application.properties generated under src/main/resources looks like:

```
# Change this to reflect where youâve checked out the code,
# specifically the entity-services-examples subdirectory
projectDir=/Users/sbalasub/git/entity-services/entity-services-examples

# These values typically do not need to be changed
# They align with the users created with mlDeploy
mlHost=localhost
mlUsername=whitney
mlPassword=********
mlRestPort=8203
mlAdminUsername=adam
mlAdminPassword=********


```

**Comment by bsrikan** [comment]
I am using Eclipse in mac and was also able to run it OK from terminal in my linux workstation.

If you are using IntelliJ, Charles had a hack in his code as below. Dont know if this is the root cause though.
```

        // FIXME this is a hack for intellij.
        if (!projectDir.endsWith("examples")) projectDir += "/entity-services-examples";

```

**Pull request merged**
