### PR TITLE
Xmlunit2 upgrade

### PR DESCRIPTION
**Pull request by grechaw**
Hi Srikanth, I'd like to discuss this PR with you.
I went about upgrading the XMLUnit 2.0 stuff, but see some things in the functional tests not passing, including what you reported in #303. 

If you could take a look at this and see what you think about incorporating, whether the remaining test adjustments are simple, etc.  I think it would be a good time to get the testing upgrade in place if we can.

### CODE REVIEW

**Comment by bsrikan** [comment]
Looks straight forward. I was working on getting functional and e2e keys updated and validating implementations from earlier PR for verbose comments removal and refactor of converter modules. Will work on this next.

**Comment by bsrikan** [comment]
build failing for functional-tests as follows. Unit tests are running fine:

```
:entity-services-functionaltests:compileTestJava
/Users/sbalasub/Desktop/ML/builds/b9_0/qa/entity-services/entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsConversionModuleGenerator.java:55: error: package sun.plugin.com.event does not exist
import sun.plugin.com.event.COMEventHandler;
                           ^
/Users/sbalasub/Desktop/ML/builds/b9_0/qa/entity-services/entity-services-functionaltests/src/test/java/com/marklogic/entityservices/TestEsSearchOptions.java:24: error: package sun.plugin.com.event does not exist
import sun.plugin.com.event.COMEventHandler;
```

**Comment by grechaw** [comment]
That import is there by mistake.  I'll remove it.  You can in the meantime probably proceed by removing the import... you will still see some issues to address

**Comment by bsrikan** [comment]
Was able to proceed after removing the import. There are failed tests as you said. 1 is due to 303 and others are pending fix to keys for refactored code. I have a PR #310 that takes care of that. We can merge this(306) and have to take care of the collisions with 310.

**Comment by grechaw** [comment]
I've added a commit to this PR that cleans up imports in the entity services and functionaltests directories.
IDEA moved imports around a lot so it touches a lot of lines.

**Comment by bsrikan** [comment]
Looks good to me.

**Pull request merged**
