### PR TITLE
Person QC Update

### PR DESCRIPTION
**Pull request by grechaw**
Had a JavaScript error in one of the tabs.

### CODE REVIEW

**Comment by bsrikan** [comment]
Please update the workspace name from XXX to Person

**Comment by grechaw** [comment]
I caught that too, and did a git push -f

**Comment by grechaw** [comment]
i won't push -f again though to reduce confusions

**Comment by jmakeig** [comment]
Forced pushes are your personal fork are fine, just not on marklogic/develop (or any shared branch).

**Comment by grechaw** [comment]
@jmakeig its slightly confusing on a PR, if people are actively looking at it, but communication about forced pushes does indeed mitigate.  We will not push -f on marklogic/* no way.

**Comment by bsrikan** [comment]
Person and Suppliers workspace look great!

**Comment by grechaw** [comment]
Latest commit e0afb59 takes care of issue #238 and also supercedes PR #239.

I refactored the loading routines to strip system-dependent parts of the path, and then changed QC to not need $PATH variable.

Lastly, tweaked logging a bit.

**Comment by jmakeig** [comment]
Paths seem to work, but I'm getting a new (probably unrelated error) on tab 11 in `races-qc.xml`: `XDMP-MODNOTFOUND: (err:XQST0059) Module /ext/Race-0.0.1-source-2.xqy not found`.

**Comment by jmakeig** [comment]
> Paths seem to work, but I'm getting a new (probably unrelated error) on tab 11 in `races-qc.xml`: `XDMP-MODNOTFOUND: (err:XQST0059) Module /ext/Race-0.0.1-source-2.xqy not found`.

Argh! The database had reverted back to `Documents` in Query Console. I don't know if that’s a workspace or Query Console bug.

**Comment by grechaw** [comment]
Think this is ready to go @jmakeig ?

**Comment by bsrikan** [comment]
There are still some errors/typos in QC. Will list them

**Comment by bsrikan** [comment]
** RACE
* Tab0:
`Once you have run the Examples Loader ('../gradlew runExampleRaces') you can step`
Change to ./gradlew. Although ../gradlew will work the same, I think @jmakeig has(or will have) ./gradlew in his EA4 write up.
* Tab2:
`let $race-f := race:extract-instance-Race(
  doc("/entity-services-examples/example-racels/data/race-data/races/10k1.json")`
Change to example-races.
* Tab7, Tab8 and Tab12:
Add explicit database and server name. Its @ Documents now.
* Tab11:
angel-island-csv files still need $PATH. Probably CSVLoader.java also needs your uri replace magic


**PERSON
* Tab0:
Change to ./gradlew.
* Tab2, Tab4:
Add explicit database and server name. Its @ Documents now.


**SUPPLIERS
* Tab0:
No readme.
* All Tabs:
Add explicit database and server name. Its @ Documents now.
* Its interesting to note that `./gradlew -PexampleDir=example-supplier mldeploy` and `./gradlew runExampleSupplier` still run as though "Suppliers" task was invoked but they dont build successfully. It gives a wrong impression that its all fine, but isnt.

**Comment by grechaw** [comment]
1. thank you for the detailed review.
2. pardon me for all the typos.

**Comment by grechaw** [comment]
OK Here are the remaining edits.

This is an interesting thing:

> that ./gradlew -PexampleDir=example-supplier mldeploy and ./gradlew runExampleSupplier still run as though "Suppliers...

What's going on is that the typo is in `example-supplier`.  Since that path is wrong, gradle just doesn't see the configuration for the example, so no extensions are loaded.
However, for gradle tasks you only have to type as many letters as needed to disambiguate, so it just calls the runExampleSuppliers task because there's nothing else it could be.  

But as you note, without successful mldeploy, the harmonization cannot happen.

**Comment by bsrikan** [comment]
Looks good!

**Comment by grechaw** [comment]
Merging now -- looks like this PR got to relax for a while over the holidays.

**Pull request merged**
