### PR TITLE
Name changes

### PR DESCRIPTION
**Pull request by grechaw**
This PR contains the change of entity-type to model.  It doesn't yet have the change of the function names, though I'll add that before merging.

As you can see it's a pretty huge commit, affecting lots of keys.  I also need to change examples to match.

I'd like you to be able to see and review this patch before we merge.
There are also server-side changes (TDE templates + schema) that are part of this change, which I'm holding ready for svn checkin.

### CODE REVIEW

**Comment by grechaw** [comment]
No contains changes to function names as well.  I'll check back later to see whether I should take the plunge and commit this to develop -- it's pretty massive and you'll want to be ready for it.

**Comment by rashiatmarklogic** [comment]
Lets talk about this one in meeting tomorrow first. There are tons of changes in this week. QA needs a heads up for major changes.

**Comment by grechaw** [comment]
Hi folks, we agreed that today sometime we'd go ahead and push this PR into develop.  Let me know when you'd like that to happen and I'll take care of it.  We can wait until Monday too if needed.

**Comment by rashiatmarklogic** [comment]
@grechaw  Charles - lets wait until Monday evening for this checkin to happen. We have some diffs that we want to discuss with you on Monday before we let this big change in the regression. I am scheduling a meeting for monday to discuss.

**Pull request merged**
