### PR TITLE
bug:40836 test and testdata changes

### PR DESCRIPTION
**Pull request by bsrikan**
Updated payloadFunctions,Required,SchemaGeneration,SearchOptions,VersionTranslatorGenerate test and xml testdata files
@grechaw @rashiatmarklogic Please review and merge for a cleaner regression test.

### CODE REVIEW

**Comment by grechaw** [comment]
I'll take a look, seems good on first glance.

**Comment by rashiatmarklogic** [comment]
Great ! Looks good tome as well at first glance. @grechaw Please merge to develop.

**Comment by grechaw** [comment]
It occurs to me you'll want to merge + push whilst I am gone -- probably without me mucking about it will be pretty straightforward

**Comment by rashiatmarklogic** [comment]
Sure Charles, we will do that - and we will only making changes in functionaltests OR examples folder at max while you are gone.

**Pull request merged**
