### PR TITLE
gradle upgrade

### PR DESCRIPTION
**Pull request by grechaw**
This PR upgrades gradle and ml-gradle.  Feel free to use it to see if it resolves locking issues

### CODE REVIEW

**Comment by bsrikan** [comment]
Thanks @grechaw . Can you please remind me of the option again to specify 1 forest per content database.

**Comment by bsrikan** [comment]
I think we would have to add an option now as required by this upgrade to undeploy.

**Comment by grechaw** [comment]
Hi @bsrikan I'm not sure what the action is on this PR.  I have another one that I'm about to make, but it doesn't have this gradle upgrade.  I can move this commit to that PR as needed.  I'll test undeploy +_deploy to see whether something obvious happens.

**Comment by bsrikan** [comment]
Closing this as the gradle upgrade has been handled via another PR.

**Pull request closed without merging**
