### PR TITLE
Extraction template update

### LINKED ISSUE #140: Extraction template should not have a column for the property when that property is locally referencing an entity type without primaryKey
Recreating from bugtrack -- this was reported 5/4 by @bsrikan 

a model:

```
 <es:definitions>
    <SchemaCompleteEntityType>
      <es:properties>
        <orderId> <!-- This is a primary Key -->
          <es:datatype>string</es:datatype>
          <es:collation>http://marklogic.com/collation/</es:collation>
        </orderId>
       <arrayreferenceInThisFile>
          <es:datatype>array</es:datatype>
          <es:description>This property refers to OrderDetails with an array declaration.</es:description>
          <es:items>
            <es:ref>#/definitions/OrderDetails</es:ref>
          </es:items>
        </arrayreferenceInThisFile>
   </SchemaCompleteEntityType>
    <OrderDetails> <!-- No primary Key -->
      <es:properties>
        <quantity> <!-- This would be primaryKey in doc2 -->
          <es:datatype>integer</es:datatype>
        </quantity>
        <productName>
          <es:datatype>string</es:datatype>
        </productName>
      </es:properties>
    </OrderDetails>
  </es:definitions>
```

A template:

```
       <template>
          <context>./arrayreferenceInThisFile</context>
          <rows>
            <row>
              <schema-name>SchemaCompleteEntityType</schema-name>
              <view-name>SchemaCompleteEntityType_arrayreferenceInThisFile</view-name>
              <columns>
                <!--
 this column joins to PK of 'parent' 
-->
                <column>
                  <name>orderId</name>
                  <scalar-type>string</scalar-type>
                  <val>../orderId</val>
                </column>
                <column>
                  <name>arrayreferenceInThisFile</name>
                  <scalar-type>string</scalar-type>
                  <val>.</val>
                </column>
                <column>
                  <name>quantity</name>
                  <scalar-type>integer</scalar-type>
                  <val>quantity</val>
                </column>
                <column>
                  <name>productName</name>
                  <scalar-type>string</scalar-type>
                  <val>productName</val>
                </column>
              </columns>
            </row>
          </rows>
        </template>
```

Bug:
In above example the column for arrayreferenceInThisFile shouldn’t be there.

### PR DESCRIPTION
**Pull request by grechaw**
Addresses issue #145 and fixes #140 .

There are a couple of functional tests that need update as a result of this -- new elements in extraction template generation.

I see I committed a fixup here inadvertently -- if you feel ready to merge then a squash would be appropriate this time.

### CODE REVIEW

**Comment by bsrikan** [comment]
I see. Will this fixup commit 	398c910 take care of #145 . I think I am confused since you mentioned inadvertently. We can merge/squash and then fix the regressions

**Comment by grechaw** [comment]
No the fixup was just supposed to go along with the other work, I just forgot to squash before hand.

**Comment by bsrikan** [comment]
Cool. Please go ahead and merge Charles! Excited to kick start EA4 👍

**Comment by grechaw** [comment]
just squashed and merged on command line, closing.

**Pull request closed without merging**
