### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by grechaw**
This PR is against develop, so it has all the commits from the other open PR as well.
The new commits fix several issues, including #318 #319 #321 .

I'll add to this PR throughout the day to knock out some of these other little bugs.

### CODE REVIEW

**Comment by bsrikan** [comment]
testInstanceGenerator() unit test needs key update for changes to attachments in instance-coverter module . 
testModelXMLConversion() unit test fails with difference in triples. Is this a key update?:
 Expected number of triples: 227
 Actual number of triples: 246

**Comment by grechaw** [comment]
Yes.  Not in the unit tests right?  I should have fixed those already.  There are new triples for namespace, namespacePrefix, and the indexes.

**Comment by bsrikan** [comment]
Yes testModelXMLConversion() in the unit tests. I think the issue is currently namespace uri is being output in place of prefixes. Example:

expected:
```
order:shortKey  a    es:RangeIndexedProperty , es:Property ;
        es:datatype  xs:short ;
        es:title     "shortKey" .
```

actual:
```
<http://marklogic.com/testing-entity-type/SchemaCompleteEntityType-0.0.1/SchemaCompleteEntityType/shortKey>
        a       <http://marklogic.com/entity-services#RangeIndexedProperty> , <http://marklogic.com/entity-services#Property> , <http://marklogic.com/entity-services#PathRangeIndexedProperty> ;
        <http://marklogic.com/entity-services#datatype>
                <http://www.w3.org/2001/XMLSchema#short> ;
        <http://marklogic.com/entity-services#title>
                "shortKey" .
```

**Comment by bsrikan** [comment]
Functional test verifySchemaValidation() fails with XDMP-REDCOMPLEXTYPE. 
#e68aa52 needs some update as you have mentioned in #322 to the commenting mechanism. Model valid-ref-simple.xml is emitting 2 definitions of:

```
<xs:complexType name="OrderDetailsContainerType">
<xs:sequence>
<xs:element ref="OrderDetails">
</xs:element>
</xs:sequence>
<xs:attribute name="datatype">
</xs:attribute>
</xs:complexType>
```

**Comment by bsrikan** [comment]
I have created 2 bugs for each of the issue mentioned above --- 325 for unit test testModelXMLConversion and 326 for functional test verifySchemaValidation().

Later today I will checkin my changes, functional tests and key updates for the bug fixes in this PR 
 and merge.

**Comment by bsrikan** [comment]
Merged.

**Pull request merged**
