### PR TITLE
build configuration update - no triggers db needed

### PR DESCRIPTION
**Pull request by grechaw**
This change to various build.gradle files skips the creation/deletion of triggers database, which we don't use.  deploy/undeploy is therefore a bit faster.

### CODE REVIEW

**Comment by grechaw** [comment]
Take a look at this -- shouldn't affect anything negatively.

**Comment by bsrikan** [comment]
Functional test build.gradle depends on project entity-services. Is that why we dont need an entry for createTriggersDatabase=false in functionaltests?

**Comment by grechaw** [comment]
that's correct @bsrikan

**Comment by grechaw** [comment]
I have added some commits to grechaw/develop and so they have been added into this PR.  Several bugfixes, ones that you reported last week all set to go.

**Comment by bsrikan** [comment]
Looks good to me!

**Comment by rashiatmarklogic** [comment]
Sure, please merge.

**Comment by grechaw** [comment]
This was merged yesterday evening.

**Pull request closed without merging**
