### PR TITLE
Version translator key updates for fixes

### PR DESCRIPTION
**Pull request by bsrikan**
This PR contains key updates for version translator bug fixes.
@grechaw  I get null on calling the convert functions for northwind data and model descriptors I use in my test. So would like to get some help from you tomorrow.

### CODE REVIEW

**Comment by grechaw** [comment]
Nice work here.  Should we resolve the nulls issue before I merge this PR?

**Comment by bsrikan** [comment]
Sure

**Comment by bsrikan** [comment]
Good to merge now @grechaw . I have added custom version-translate xqy module and added a test to call convert-instance with source data envelopes. But this PR requires your commit #41a11e0 to be merged to develop for the tests to pass.

**Comment by grechaw** [comment]
About to merge this PR, sorry it took longer than expected.

**Pull request merged**
