### PR TITLE
Remove administrative roles and users from examples and e2e

### PR DESCRIPTION
**Pull request by grechaw**
This PR removes roles and users associated with administering examples, in favor of the single administration point, Mr. admin.

@bsrikan , will proceed at your signal.  This does change e2e folder as well as examples.

### CODE REVIEW

**Comment by bsrikan** [comment]
@grechaw with this implementation:

1> I think it forces e2e to switch over to multiproject like settings. I get an error:
`Unable to insert content at URI: /ext/Northwind-0.0.1-source-2.xqy; cause: Role does not exist`

2> Is there a way to deploy races, for example from parent dir rather than examples dir

3> (Not related to this PR) Do run tasks always run pointing to localhost or can it be configured to point to whatever mlHost is pointed to in gradle.properties? I was trying to "run" from my mac with host pointed to my linux workstation and got an exception as so:
`Connection to http://localhost:8203 refused 75% > :entity-services-examples:runExamplePerson`
Note that port 8203 does exist in my workstation

**Comment by grechaw** [comment]
Your extension may require a change.  

#1 I think is because the user/role in src/main/resources/application.properties no longer exists.

#2 the examples will only deploy from the examples directory.  Teasing apart the project layers was important to get some consistency.   Is it needed for some reason to deploy examples from parent?  I put the gradle wrapper into the subproject in order to make that more obvious.

#3 Is this during use of DMSDK?  Data Movement actually does use MarkLogic's configured hostname, which is generally not 'localhost'.  What I have to do (and if you ever set up a cluster you'll be familiar with this need) is to edit your hosts file to add an alias for that hostname to point to 127.0.0.1

**Comment by jmakeig** [comment]
>  edit your hosts file to add an alias for that hostname to point to 127.0.0.1

Or rename your MarkLogic host `localhost`.

**Comment by grechaw** [comment]
> Or rename your MarkLogic host localhost.

Mind blown for the day :+1:

**Comment by bsrikan** [comment]
1. Examples also has adam in application.properties which no longer exists, but I dont get any error there.

2. I was under the impression that we are changing implementation so folks can run examples from parent dir. Guess we did this so they dont run into auth error while running mldeploy from parent -- which is achieved now. I am good as long as we make it clear to people trying out examples that they have to do so from "examples" dir

3. If we expect everybody who tries this out, to have marklogic installed in their laptop then there is no problem. If there are people who would have marklogic installed in a remote machine and they try running examples from local would we ask them to rename Marklogic host to `localhost`

**Comment by bsrikan** [comment]
OK. So (1) worked after I took out nwind-admin from application.properties in e2e.

**Comment by grechaw** [comment]
The examples work when running against another machine too, except for code generation.  code generation uses xdmp:save, so it saves things on the server rather than the client machine.  This doesn't affect running, but does affect the getCode gradle task.

So it's just that the hostname that marklogic has must be addressable from the client, either via hosts file, DNS, or by naming the MarkLogic server localhost (on localhost)

**Comment by bsrikan** [comment]
Good to merge to develop

**Pull request merged**
