### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by grechaw**
These two commits fix issue #252 and also the issue with nulls in example-races #246 

We've talked about this already @bsrikan  so let me know whether you think it's good to go.

### CODE REVIEW

**Comment by bsrikan** [comment]
Applying #5899e19 did not get rid of null cells for me. I still get duplicates/null as a result of cross product.

**Comment by grechaw** [comment]
Well, did you edit the example templates to match the new generated one?

**Comment by bsrikan** [comment]
I tried in my e2e and did edit the templates to match the new generated one. When I ran example-races by editing the example template to include [es:info/es:version = "0.0.1"] I could see that the issue was resolved and there was no duplicate or null data.
Although there are 2 notable differences in the schemas folder of e2e and examples:

- Race-0.0.1.tdex does not match the new generated extraction template. There is no $RDF or triples element
- example-races schema dir only has Race-0.0.1.tdex whereas e2e-nwind has both versions of tdex

**Comment by bsrikan** [comment]
Basically I am saying that the change isnt working for e2e. Still see null/duplicate records.
Works for example-races, but race-0.0.1.tdex doesnt match latest generated extraction template.

**Comment by grechaw** [comment]
"race-0.0.1.tdex doesnt match latest generated extraction template."  The change for #252 enforces this behavior and I think that's good.  For e2e, there may be some other cardinality issue, but templates should be such that they only match one set of data (if there are two versions of instances, they should not be treated as duplicates within a TDE view).

Is e2e pullable?  I'm curious to see what you're seeing.

**Comment by bsrikan** [comment]
@grechaw and I met over webex and found that to mitigate null/duplicate records:

- in migration scenarios from model1 to model2 one should rename <schema-name> in tdex of one version in order to have 2 active views
- in such cases having <view-layout> set to sparse doesnt do anything and is possibly not required
- deleting envelopes from model1 and having envelopes from model2 alone in the db also would help based on the implementation in this PR. This is because both tdes will now have context set based on version.

This PR is good to go.

**Pull request merged**
