### PR TITLE
ml-gradle update issue #130

### PR DESCRIPTION
**Pull request by grechaw**
Hi @bsrikan we should merge this fix to take advantage of new ml-gradle fixes.

### CODE REVIEW

**Comment by bsrikan** [comment]
I see. Is there a better way to get updated ml-gradle than having to update build.gradle in parent project.

**Comment by grechaw** [comment]
If you want different versions in different sub projects, one would configure it there.  The parent project is the right place to configure this.  I think it was just an oversight by @jmakeig cause he hasn't suffered enough gradle yet.

**Comment by bsrikan** [comment]
I agree that parent project is where it should be configured. My concern was if tomorrow Rob has a new ml-gradle version, we would have to keep updating the build.gradle file right. So is there an alternative to that?

**Comment by grechaw** [comment]
Um.  This is *the* way to declare a dependency.  I guess some dependency managers like for python you can specify "newer than version X" but Java has always avoided that kind of thing.  We would never want to release code on an untested release of ml-gradle, so it's crucial to always have these version numbers managed.  I don't think you would want an alternate method.

**Comment by bsrikan** [comment]
Alright. Thanks for explaining why this is the way to go about it. Merging!

**Comment by grechaw** [comment]
Thanks @bsrikan !

**Pull request merged**
