### PR TITLE
Added tests to verify exception when there is zero entity type

### PR DESCRIPTION
**Pull request by bsrikan**
@grechaw Please review and merge changes 190fcdb and 47f5232.
faa0bda and 08dd15d can be ignored and not merged.
@rashiatmarklogic 

Thanks,
Srikanth

### CODE REVIEW

**Comment by grechaw** [comment]
Hi @bsrikan I'll merge your changes. commit 08dd15dfe7afe7a05c3663ac68232a9f516f9539 is an example of an unnecessary merge -- you'll note there are 0 lines added and 0 lines removed.  If you'd used rebase instead of merge, this commit would not have appeared in your history.

**Comment by grechaw** [comment]
like you said in your comment.

**Comment by bsrikan** [comment]
Agreed. I realized only after that I should have rebased than merge.

**Comment by grechaw** [comment]
You'll have to push -f back to your repo when I ignore the two empty commits btw

**Pull request merged**
