### PR TITLE
Issues #351, #349. edits to version translator

### PR DESCRIPTION
**Pull request by grechaw**
This commit contains a fix to version translation codegen from issue #351, as well as the small typo-ish fix to #349.  
Unit tests are all good with this update.
The change is a code cleanup too -- it looks a little bigger than it would otherwise, but theres a normalization in the generated code that makes it more readable and understandable IMO.

### CODE REVIEW

**Comment by bsrikan** [comment]
Looks good. Functional tests are all good too with updates to couple of keys for version translator fix for #349. 
examples and e2e also looking good. OK to merge.

**Comment by bsrikan** [comment]
Before you merge can you update where it sets $src-node to $source-node.

**Comment by bsrikan** [comment]
Maybe I spoke too soon.. It is ok as it is in your PR right.

**Comment by grechaw** [comment]
Actually, yes I wanted to have a unique name in that function call, though it is perhaps a cheat to name as i did.

**Comment by bsrikan** [comment]
OK to merge.

**Comment by grechaw** [comment]
Merged

**Pull request closed without merging**
