### PR TITLE
Feature/msb example

### PR DESCRIPTION
**Pull request by sastafford**
@grechaw - I was looking at your ExamplesLoader last week and I got the idea to implement the same functionality using MarkLogic Spring Batch.  It's a side project that I'm working on for batch processing in MarkLogic.  It actually fits into the Spring Batch framework quite nicely.  

FYI - @sammefford, @rjrudin, @jmakeig, @paxtonhare  

Steps

1. importJsonData - I could add an extra step to load the models separately, but I'm just assuming they are already loaded in the modules database under /ext.  The parts for this step were written to facilitate another job that loads JSON in MarkLogic.  
2.  importCsvData - Loads the third party CSV file.  I'm using out of the box classes supplied by Spring Batch. 
3. Harmonizer step - borrowed from your existing code
4. Translator step - borrowed from your existing code
5. I skipped your code generator step but that could be done as well.  

Here are the collections and counts after running the job.  
csv 200
race-0.0.2-envelopes 4
race-envelopes 4
raw 1354
run-envelopes 1100

### CODE REVIEW

**Comment by grechaw** [comment]
This is really interesting.  I'll get it running, try to grok all the annotations and how Spring Batch is put together, then merge later this week.

**Comment by sastafford** [comment]
I did not ingest the triples but that could be added on as well.

**Comment by jmakeig** [comment]
@sastafford This looks really good. However, I think we need to be careful about cognitive overload in the Entity Services examples. One should not need to understand Spring Batch to learn Entity Services. (Yes, the same could be said about DMSDK here.) I think this example would make more sense in the MarkLogic Spring Batch repo to demonstrate a particular type of processing with Spring Batch.

**Comment by sastafford** [comment]
@jmakeig - fair assessment, my feelings would not be hurt if this example were left out of this repo.  

I wanted to prove to myself and show that this data hub pattern of ingest raw/harmonize/transform is a good use case for Spring Batch.

**Comment by grechaw** [comment]
Regarding the entity descriptors themselves -- they go into the content database.   They're useful there because, in consort with TDE, you can query model and instance data together.

**Comment by jmakeig** [comment]
> I wanted to prove to myself and show that this data hub pattern of ingest raw/harmonize/transform is a good use case for Spring Batch.

@sastafford Yes, that sounds like a **great** Spring Batch example.

**Comment by grechaw** [comment]
@sastafford Do you want to take this patch and make an example in marklogic spring batch with it?
I think this is really great stuff and that folks will find it very useful as an example for writing integration code w spring

**Comment by sastafford** [comment]
Go ahead and close this pull request.  I'll go ahead and integrate it as an example in my MSB repository.

**Pull request closed without merging**
