### PR TITLE
Schemas namespaces

### PR DESCRIPTION
**Pull request by grechaw**
Issue #316 is implemented in this PR.  I owe you all a spec update to describe what I've done here.

### CODE REVIEW

**Comment by bsrikan** [comment]
Unit tests verifyDualNamespaceModel() and verifySchemaValidation() still fail for me. How about you @grechaw ?

**Comment by bsrikan** [comment]
Spoke too soon I think. Let me soft link the xdmp files in this checkin and try again.

**Comment by bsrikan** [comment]
Ok so testModelXmlConversion() still fails for me. All other tests run ok.

**Comment by grechaw** [comment]
what's your failure for testModelXmlConversion -- number of triples?

**Comment by bsrikan** [comment]
yes number of triples.
In functional tests, verifySchemaValidation() test fails with XDMP-REDCOMPLEXXTYPE: Redefined complex type. I have validated that the test instances generated look OK. Not sure what this error is.

**Comment by grechaw** [comment]
XDMP-REDCOMPLEXXTYPE this error indicates that a schema in emitting two definitions for the same type.  I may have messed up the commenting mechanism, so I'll go looking for this error.

When i was developing the schema changes, I had to make sure the schemas db was empty before running the tests.  If I'd left anything in there the tests would fail in erratic ways.  But that's probably not happening to you.

**Pull request closed without merging**
