### PR TITLE
Fix example security

### PR DESCRIPTION
**Pull request by grechaw**
There should be just one commit in this PR, because the outstanding one is causing a little confusion.  This commit fixes the issue you found with deploying versions

### CODE REVIEW

**Comment by grechaw** [comment]
OK, I fixed my branches.  This PR contains the two commits from the other open one, so we'll want to merge that one before this looks clean.

**Comment by grechaw** [comment]
Cleaned up this PR

**Comment by bsrikan** [comment]
Transforms use obsolete users to give permission to envelopes. Needs update.

**Comment by grechaw** [comment]
Indeed, I've been surprised at how many place the roles pop up.
Seems as though, were we to do more involved security examples, we'd find a lot of places where managing security could be easier, or at least more automated.

**Comment by grechaw** [comment]
Hi @bsrikan I got this updated and verified by running the following:

```
./gradlew -PexampleDir=example-person mlDeploy runExamplePerson mlUndeploy
./gradlew -PexampleDir=example-races mlDeploy runExampleRaces mlUndeploy
./gradlew -PexampleDir=example-suppliers mlDeploy runExampleSuppliers mlUndeploy
./gradlew -PexampleDir=example-versions mlDeploy runExampleVersions mlUndeploy
```

**Comment by bsrikan** [comment]
OK. Races `deploy` and `run` fine now as do versions, suppliers and person examples. Funny how schemas gets missed if you say `example-supplier` instead of `example-suppliers`.

As you have already noticed, Xquery Optic examples are failing for Races-Tab9 and Suppliers-Last tab

**Comment by grechaw** [comment]
well, if you say `example-supplier` then the database is not configured, that makes sense.

**Comment by grechaw** [comment]
So I've filed a bug for qconsole issue, is this PR ready to go?  I think we've addressed all the concerns.

**Comment by bsrikan** [comment]
Yes @grechaw  Good to go!

**Comment by grechaw** [comment]
OK This PR has been merged, thanks @bsrikan

**Pull request closed without merging**
